version: 2
updates:
  - package-ecosystem: npm
    directory: "/packages/steamdown"
    schedule:
      interval: daily
  - package-ecosystem: npm
    directory: "/"
    groups:
      typescript-eslint:
        patterns:
          - "@typescript-eslint/*"
      jest:
        patterns:
          - "jest"
          - "@jest/*"
    schedule:
      interval: weekly
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
