changelog:
  exclude:
    labels:
      - ignore-for-release
    authors:
      - dependabot
  categories:
    - title: Breaking changes
      labels:
        - breaking
    - title: New features
      labels:
        - feature
    - title: Fixes
      labels:
        - bug
    - title: Other changes
      labels:
        - "*"
