# NOTE: This is a dummy CI to run and pass when the path is ignored
#       See https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/managing-protected-branches/troubleshooting-required-status-checks#handling-skipped-but-required-checks
name: CI
on:
  pull_request:
    branches: ["main"]
    paths-ignore: ["packages/steamdown/**"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: 'echo "No build required"'
