name: Documentation
on:
  push:
    branches: ["main"]

jobs:
  docs:
    name: Deploy documentation
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deploy.outputs.page_url }}
    steps:
      - uses: actions/checkout@v7
      - uses: docmd-io/deploy@v1.1
        id: build
      - uses: actions/upload-pages-artifact@v5
        with:
          path: ${{ steps.build.outputs.site-dir }}
      - uses: actions/deploy-pages@v5
        id: deploy
